In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("population-and-growth-rates-by-districts-of-census-1951-2017-in-punjab-pakistan.csv")

In [3]:
df.head()

,Province/division/ district,Population ( in '1000' ) in 1951,Population ( in '1000' ) in 1961,Population ( in '1000' ) in 1972,Population ( in '1000' ) in 1981,Population ( in '1000' ) in 1998,Population ( in '1000' ) in 2017,Average annual growth rate (%) in 1961,Average annual growth rate (%) in 1972,Average annual growth rate (%) in 1981,Average annual growth rate (%) in 1998,Average annual growth rate (%) in 2017
0,PUNJAB,"20,541","25,464","37,607","47,292","73,621","109,990",2.19,3.41,2.75,2.64,2.13
1,Bahawalpur Division,"1,823","2,574","3,544","4,669","7,636","11,453",3.54,2.79,3.32,2.93,2.15
2,Bahawalnagar,630,823,"1,074","1,374","2,061","2,976",2.72,2.32,2.96,2.41,1.95
3,Bahawalpur,528,736,"1,071","1,453","2,433","3,669",3.40,3.29,3.68,3.08,2.18
4,Rahim Yar Khan,664,"1,016","1,399","1,841","3,141","4,808",4.37,2.79,3.31,3.19,2.26

# Implementation Task
Using the same dataset from Day 3:
- Identify and handle all missing values (drop or fill with justification)
- Fix any wrong data types (e.g. numeric columns stored as strings)
- Remove duplicates
- Create 2 new derived columns using .apply() or vectorized operations
- Reshape the data using either .pivot_table() or .groupby() + .agg() to produce a summary table
- Merge it with a second small manually created DataFrame to add extra context (e.g. mapping a column to a category label)
  
Deliverable: day4_pandas_cleaning.ipynb — same notebook style as Day 3, each step clearly labeled with a markdown cell explaining your reasoning.

### Step 1. Identify and handle missing values

In [4]:
df.isnull().sum()

Province/division/ district                0
Population ( in '1000' ) in 1951           0
Population ( in '1000' ) in 1961           0
Population ( in '1000' ) in 1972           0
Population ( in '1000' ) in 1981           0
Population ( in '1000' ) in 1998           0
Population ( in '1000' ) in 2017           0
Average annual growth rate (%) in 1961     0
Average annual growth rate (%) in  1972    0
Average annual growth rate (%) in  1981    0
Average annual growth rate (%) in  1998    0
Average annual growth rate (%) in  2017    0
dtype: int64

This dataset did not contain any missing values.

If there had been missing values, I could have handled them in different ways depending on the situation.

### Option 1: Remove rows with missing values

```python
df = df.dropna()
```

This removes every row that contains at least one missing value.

### Option 2: Fill missing numeric values

```python
df["population_2017"] = df["population_2017"].fillna(df["population_2017"].mean())
```

This replaces missing values with the column's average.

### Option 3: Fill missing text values

```python
df["region"] = df["region"].fillna("Unknown")
```

This replaces missing text values with a placeholder.

Since my dataset contained no missing values, none of these methods were necessary.

### Step 2. Fix wrong data types

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 12 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Province/division/ district              46 non-null     str
 1   Population ( in '1000' ) in 1951         46 non-null     str
 2   Population ( in '1000' ) in 1961         46 non-null     str
 3   Population ( in '1000' ) in 1972         46 non-null     str
 4   Population ( in '1000' ) in 1981         46 non-null     str
 5   Population ( in '1000' ) in 1998         46 non-null     str
 6   Population ( in '1000' ) in 2017         46 non-null     str
 7   Average annual growth rate (%) in 1961   46 non-null     float64
 8   Average annual growth rate (%) in  1972  46 non-null     float64
 9   Average annual growth rate (%) in  1981  46 non-null     float64
 10  Average annual growth rate (%) in  1998  46 non-null     float64
 11  Average annual growth rate (%) in  2017  46 non-null     float64
dtypes: float64(5), str(7)
memory usage: 4.4 KB

In [10]:
df.columns = [
    "region",
    "population_1951",
    "population_1961",
    "population_1972",
    "population_1981",
    "population_1998",
    "population_2017",
    "growth_1961",
    "growth_1972",
    "growth_1981",
    "growth_1998",
    "growth_2017"
]

In [11]:
for col in population_cols:
 df[col] = df[col].str.replace(",", "").astype(int)

The population columns were stored as strings because they contained commas.

I removed the commas and converted the columns to integers so numerical calculations could be performed.

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           46 non-null     str
 1   population_1951  46 non-null     int64
 2   population_1961  46 non-null     int64
 3   population_1972  46 non-null     int64
 4   population_1981  46 non-null     int64
 5   population_1998  46 non-null     int64
 6   population_2017  46 non-null     int64
 7   growth_1961      46 non-null     float64
 8   growth_1972      46 non-null     float64
 9   growth_1981      46 non-null     float64
 10  growth_1998      46 non-null     float64
 11  growth_2017      46 non-null     float64
dtypes: float64(5), int64(6), str(1)
memory usage: 4.4 KB

### Step 3. Remove duplicates

first check if there are any duplicates

In [14]:
df.duplicated().sum()

np.int64(0)

This dataset did not contain any duplicate rows.

I checked for duplicates using:

```python
print(df.duplicated().sum())
```

Output:

```text
0
```

Since the output is `0`, no rows were duplicated, so no action was needed.

If duplicate rows had existed, I could have removed them using:

```python
df = df.drop_duplicates()
```

This removes duplicate rows while keeping the first occurrence by default.

If I wanted to remove duplicates based on only specific columns, I could use:

```python
df = df.drop_duplicates(subset=["region"])
```

This checks only the `region` column for duplicates and keeps the first occurrence.

### Step 4. Create TWO derived columns

Here I havre made two derived cols, one using vectorized operation and the other using .apply().
- Derived Column 1 (vectorized)

  To calculate increase in population

In [15]:
df["population_increase"] = df["population_2017"] - df["population_1951"]

In [28]:
df[["region", "population_1951", "population_2017", "population_increase"]].head(10)

                region  population_1951  population_2017  population_increase
0               PUNJAB            20541           109990                89449
1  Bahawalpur Division             1823            11453                 9630
2         Bahawalnagar              630             2976                 2346
3           Bahawalpur              528             3669                 3141
4       Rahim Yar Khan              664             4808                 4144
5    D.G.Khan Division             1379            11021                 9642
6             D.G.Khan              384             2873                 2489
7               Layyah              162             1824                 1662
8         Muzaffargarh              589             4329                 3740
9             Rajanpur              244             1996                 1752

- Derived Column 2 (.apply())

  To classify regions

In [20]:
def region_size(population):
    if population >= 10000:
        return "Very Large"
    elif population >= 5000:
        return "Large"
    else:
        return "Small"

df["region_size"] = df["population_2017"].apply(region_size)

In [31]:
df[["region", "population_2017", "region_size"]].head(10)

                region  population_2017 region_size
0               PUNJAB           109990  Very Large
1  Bahawalpur Division            11453  Very Large
2         Bahawalnagar             2976       Small
3           Bahawalpur             3669       Small
4       Rahim Yar Khan             4808       Small
5    D.G.Khan Division            11021  Very Large
6             D.G.Khan             2873       Small
7               Layyah             1824       Small
8         Muzaffargarh             4329       Small
9             Rajanpur             1996       Small

I created two new columns.

- `population_increase` using a vectorized operation.
- `region_size` using `.apply()` to classify each region according to its 2017 population.

### Step 5. Reshape the data

In [22]:
summary = df.groupby("region_size").agg(
    average_population=("population_2017", "mean"),
    average_growth=("growth_2017", "mean"),
    number_of_regions=("region", "count")
)

In [23]:
summary

             average_population  average_growth  number_of_regions
region_size
Large               6768.000000         2.03600                  5
Small               2517.937500         1.98125                 32
Very Large         23950.555556         2.28000                  9

I grouped the dataset by `region_size` and calculated:

- average population
- average growth rate
- number of regions

This creates a summary table for each category.

### Step 6. Merge with another DataFrame

In [24]:
# Synthetic dataFrame that I created manually for this step
category_info = pd.DataFrame({
    "region_size": ["Small", "Large", "Very Large"],
    "description": [
        "Population below 5,000",
        "Population between 5,000 and 9,999",
        "Population of 10,000 or more"
    ]
})

In [25]:
category_info

  region_size                         description
0       Small              Population below 5,000
1       Large  Population between 5,000 and 9,999
2  Very Large        Population of 10,000 or more

In [26]:
merged_df = pd.merge(
    df,
    category_info,
    on="region_size",
    how="left"
)

In [27]:
merged_df.head()

,region,population_1951,population_1961,population_1972,population_1981,population_1998,population_2017,growth_1961,growth_1972,growth_1981,growth_1998,growth_2017,population_increase,region_size,description
0,PUNJAB,20541,25464,37607,47292,73621,109990,2.19,3.41,2.75,2.64,2.13,89449,Very Large,"Population of 10,000 or more"
1,Bahawalpur Division,1823,2574,3544,4669,7636,11453,3.54,2.79,3.32,2.93,2.15,9630,Very Large,"Population of 10,000 or more"
2,Bahawalnagar,630,823,1074,1374,2061,2976,2.72,2.32,2.96,2.41,1.95,2346,Small,"Population below 5,000"
3,Bahawalpur,528,736,1071,1453,2433,3669,3.40,3.29,3.68,3.08,2.18,3141,Small,"Population below 5,000"
4,Rahim Yar Khan,664,1016,1399,1841,3141,4808,4.37,2.79,3.31,3.19,2.26,4144,Small,"Population below 5,000"

I created a small DataFrame containing descriptions for each region size.

I then merged it with the main dataset using `.merge()` to add extra context.